FROM alpine:3.9.4

# add all packages
RUN apk update && apk upgrade && apk add \
	apache2 \
	php7 \
	php7-apache2 \
	php7-gd \
	php7-mysqli \
	php7-json \
	php7-phar \
	php7-iconv \
	php7-mbstring \
	php7-zlib \
	php7-curl \
	php7-session \
	php7-redis \
	php7-mysqli \
	php7-pdo \ 
	php7-pdo_mysql \
	php7-tokenizer \
	php7-dom \
	php7-simplexml \
	php7-xmlreader \
	php7-xmlwriter \
	php7-xmlrpc \
	curl \
	&& curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer 

# place php 7 into php directy and purge package cache
RUN cp /usr/bin/php7 /usr/bin/php \
    && rm -f /var/cache/apk/*

# setup apache
RUN \
    sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_module/LoadModule\ session_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_cookie_module/LoadModule\ session_cookie_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ session_crypto_module/LoadModule\ session_crypto_module/" /etc/apache2/httpd.conf \
    && sed -i "s/#LoadModule\ deflate_module/LoadModule\ deflate_module/" /etc/apache2/httpd.conf \
    && sed -i "s#^DocumentRoot \".*#DocumentRoot \"/var/app/public_html\"#g" /etc/apache2/httpd.conf \
    && sed -i "s#/var/www/localhost/htdocs#/var/app/public_html#" /etc/apache2/httpd.conf \
    && printf "\n<Directory \"/var/app/public_html\">\n\tAllowOverride All\n</Directory>\n" >> /etc/apache2/httpd.conf

# setup entrypoint file and apply execution rights
ADD ./entrypoint.sh /bootstrap/entrypoint.sh
RUN chmod +x /bootstrap/entrypoint.sh

# expose on port 80 and set workdir
EXPOSE 80
WORKDIR /var/app

# send it
ENTRYPOINT ["/bootstrap/entrypoint.sh"]